import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '@constants/theme';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    backgroundColor: '#101820',
  },
  imageStyle: {
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContent: {
    flexGrow: 1,
    padding: 16,
    paddingHorizontal: 24,
  },
  mainContainer: {
    flex: 1,
    padding: 16,
    paddingHorizontal: 24,
  },
  cameraListScroll: {
    flex: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
  },
  headerInfo: {
    flex: 1,
  },
  userName: {
    color: 'rgba(255,255,255,0.7)',
    fontWeight: FONTS.weights.regular,
    fontSize: 14,
  },
  subTitle: {
    color: COLORS.background,
    fontSize: 18,
    fontWeight: FONTS.weights.semiBold,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 12,
  },
  iconBtn: {
    marginLeft: 14,
  },
  headerIcon: {
    width: 28,
    height: 28,
    tintColor: 'white',
  },
  title: {
    marginTop: 23,
    marginBottom: 8,
  },
  titleText: {
    color: COLORS.background,
    fontWeight: FONTS.weights.bold,
    fontSize: 28,
    marginBottom: 4,
  },
  filterRow: {
    flexDirection: 'row',
    marginBottom: 25,
    maxHeight: 37,
  },
  filterBtn: {
    backgroundColor: 'rgba(24, 54, 86, 0.6)',
    borderRadius: 40,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#B5D2FE',
    height: 37,
  },
  filterText: {
    color: COLORS.background,
    fontWeight: FONTS.weights.medium,
    fontSize: 16,
  },
  card: {
    backgroundColor: '#1A202C',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    height: 340,
  },
  videoWrapper: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  cardImage: {
    width: '100%',
    height: 260,
    borderRadius: 12,
  },
  cardBadge: {
    position: 'absolute',
    right: 40,
    top: 40,
    backgroundColor: 'rgba(255,255,255,0.4)',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.FF0000,
    marginRight: 6,
  },
  badgeText: {
    color: COLORS.background,
    fontSize: 16,
    fontWeight: FONTS.weights.medium,
  },
  cardText: {
    color: '#fff',
    fontWeight: FONTS.weights.medium,
    fontSize: 20,
    marginTop: 20,
    marginBottom: 20,
    flex: 1,
  },
  addCameraBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    marginTop: 8,
  },
  addCameraText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    marginLeft: 18,
    marginRight: 8,
  },
  cameraIcon: {
    width: 28,
    height: 28,
    marginRight: 6,
    tintColor: '#fff',
  },
  arrowIcon: {
    width: 28,
    height: 28,
    tintColor: '#fff',
  },
  activeFilterBtn: {
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconCircle: {
    alignItems: FONTS.align.alignSelfEnd,
  },
  manualButton: {
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 32,
    paddingVertical: 8,
    paddingHorizontal: 20,
    height: 64,
    borderWidth: 1.5,
    borderColor: '#39FFF9',
    backgroundColor: 'rgba(20,24,32,0.25)',
    marginTop: 18,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 6,
  },
  manualButtonText: {
    fontSize: 18,
    fontWeight: FONTS.weights.medium,
    color: COLORS.background,
  },
  textStyleReady: {
    color: COLORS.background,
    fontSize: 28,
    fontWeight: FONTS.weights.bold,
    textAlign: 'center',
  },
  textCameraAndEnsure: {
    color: COLORS.background,
    fontSize: 16,
    fontWeight: FONTS.weights.regular,
    marginLeft: 5,
  },
  styleEmptyList: {
    flex: 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  styleBottomText: {
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 40,
    left: 16,
    right: 16,
    alignSelf: 'stretch',
  },
  styleTextFlashing: {
    color: COLORS.background,
    marginLeft: 5,
  },
  styleGetHelp: {
    color: COLORS.main,
  },
  styleViewCameraAndEnsure: {
    flexDirection: 'row',
  },
  paddingScrollView: {
    paddingBottom: 16,
  },
  loadingMore: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  positionButtonBottom: {
    position: 'absolute',
    right: 20,
  },
  viewAddCamera: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    position: 'relative',
  },
  badgeContainer: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FF0000',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  badgeTextNoti: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
