sonar.projectKey=Timima01-app
sonar.qualitygate.wait=true
sonar.projectVersion=1.0.0

# Source and test paths
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Exclusions
sonar.exclusions=**/*.test.ts,**/*. test.tsx,**/node_modules/**,**/coverage/**,**/*.styles.ts,**/android/**,**/ios/**,**/__tests__/**

# Coverage
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Quality Gate
sonar.qualitygate.wait=true

# Language
sonar.language=ts
