import { StyleSheet } from 'react-native';
import { isTablet } from '@utils/responsive';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0B1117', paddingHorizontal: 0 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 8,
    marginBottom: isTablet() ? 20 : 12,
  },
  backBtn: { marginRight: 5, padding: 4 },
  headerTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '700',
    marginLeft: 20,
  },
  // Code sticker mock
  stickerBoxOuter: {
    borderRadius: 20,
    borderWidth: 2.5,
    borderColor: '#244C70',
    backgroundColor: '#131C2C',
    width: 250,
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stickerBoxInner: {
    flex: 1,
    width: 184,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 8,
  },
  stickerBoxLines: {
    marginBottom: 8,
  },
  stickerBoxLineLong: {
    height: 15,
    backgroundColor: '#334C6C',
    borderRadius: 10,
    width: 120,
    marginBottom: 4,
  },
  stickerBoxLineShort: {
    height: 10,
    backgroundColor: '#393b4b',
    borderRadius: 10,
    width: 60,
    marginBottom: 2,
  },
  stickerBoxCodeRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 7,
    marginTop: 5,
  },
  stickerBoxCodeItem: {
    width: 30,
    height: 40,
    borderRadius: 6,
    backgroundColor: '#101522',
    borderWidth: 1.1,
    borderColor: '#223456',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stickerBoxCodeText: {
    color: '#2A82EE',
    fontWeight: '700',
    fontSize: 18,
    textAlign: 'center',
    letterSpacing: 1.2,
  },
  // Texts
  title: {
    fontSize: 17,
    color: '#FFF',
    textAlign: 'center',
    fontWeight: '800',
    marginTop: 7,
    marginBottom: 0,
    letterSpacing: 0.7,
  },
  instruction: {
    textAlign: 'center',
    color: '#A7B8CC',
    fontSize: 13,
    marginHorizontal: 18,
    marginBottom: 14,
    marginTop: 3,
    fontWeight: '400',
  },
  // Code input
  codeInputsRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    marginBottom: 12,
    marginTop: 8,
  },
  codeInput: {
    width: 46,
    height: 46,
    backgroundColor: '#1B2236',
    color: '#FFF',
    fontSize: 22,
    borderRadius: 12,
    borderWidth: 1.6,
    borderColor: '#39445A',
    fontWeight: '700',
    textAlign: 'center',
  },
  errText: { color: '#FF5E6C', textAlign: 'center', marginTop: 2, fontSize: 13, marginBottom: 2 },
  helpRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    marginTop: 6,
    marginBottom: 16,
  },
  helpText: { color: '#90A9C9', fontSize: 12, flex: 1, fontWeight: '500', lineHeight: 18 },
  pairBtn: {
    marginTop: 7,
    backgroundColor: '#49C6FF',
    borderRadius: 56,
    paddingVertical: 13,
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  pairBtnDisabled: {
    backgroundColor: '#817d7d',
  },
  pairBtnText: { color: '#112837', fontSize: 17, fontWeight: '800' },
  pairBtnTextDisabled: { color: '#666666' },
  cannotRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 17,
  },
  cannotText: {
    color: '#A7E9FF',
    fontWeight: '700',
    fontSize: 15,
    marginLeft: 7,
    textDecorationLine: 'underline',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    backgroundColor: '#101820',
  },
  imageStyle: {
    width: '100%',
    height: '100%',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonIcon: {
    width: isTablet() ? 50 : 46,
    height: isTablet() ? 50 : 46,
  },
  scrollView: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
    marginTop: 35,
  },
  spacer: {
    flex: 1,
  },
  codeStickerContainer: {
    backgroundColor: '#1A2332',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 280,
    width: '80%',
  },
  bottomContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  marginRightIcon: {
    marginRight: 4,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingContent: {
    backgroundColor: 'rgba(26, 42, 58, 0.95)',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#38E9FF',
  },
  loadingText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 15,
    textAlign: 'center',
  },
});
