import { StyleSheet } from 'react-native';
import { isTablet } from '@utils/responsive';
import { COLORS, FONTS } from '@constants/theme';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    backgroundColor: '#101820',
  },

  imageStyle: {
    width: '100%',
    height: '100%',
  },
  absoluteFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  slide: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: isTablet() ? 80 : 18,
  },
  cameraWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  realViewBtn: {
    position: 'absolute',
    backgroundColor: 'rgba(180,180,180,0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    paddingHorizontal: isTablet() ? 16 : 12,
    paddingVertical: isTablet() ? 15 : 4,
    top: isTablet() ? 80 : 10,
    right: isTablet() ? 50 : 10,
  },
  realViewText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: isTablet() ? 25 : 16,
    marginLeft: 10,
  },
  liveStreamBtn: {
    position: 'absolute',
    backgroundColor: 'rgba(180,180,180,0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    paddingHorizontal: isTablet() ? 16 : 12,
    paddingVertical: isTablet() ? 15 : 4,
    bottom: 0,
    left: 10,
  },
  liveStreamText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: isTablet() ? 25 : 16,
    marginLeft: 10,
  },
  paginationWrapper: {
    position: 'absolute',
    bottom: 74,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  arrowBtn: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    backgroundColor: 'rgba(50,50,60,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 18,
  },
  arrow: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '900',
  },
  dotsWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dot: {
    backgroundColor: '#fff',
    opacity: 0.5,
    width: isTablet() ? 15 : 9,
    height: isTablet() ? 15 : 9,
    borderRadius: 6,
    marginHorizontal: 5,
  },
  activeDotWrapper: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeDot: {
    width: 12,
    height: 12,
    opacity: 1,
    borderRadius: 7,
    backgroundColor: '#fff',
  },
  arrowBtnDisabled: {
    opacity: 0.3,
  },
  header: {
    alignItems: 'center',
    flex: isTablet() ? 0.3 : 0.5,
    justifyContent: 'center',
    marginTop: 34,
  },
  headerTablet: {
    paddingTop: 4,
    paddingBottom: 8,
  },
  headerText: {
    fontSize: isTablet() ? 50 : 37,
    color: COLORS.background,
    fontWeight: FONTS.weights.bold,
    marginTop: 38,
    textAlign: 'center',
  },
  slideInner: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginTop: 0,
  },
  iconBottomSize: {
    width: isTablet() ? 55 : 38,
    height: isTablet() ? 55 : 38,
  },
  styleLandscape: {
    alignItems: 'center',
    paddingBottom: 120,
  },
  manualButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 40,
    padding: 16,
    minHeight: 72,
    marginHorizontal: 24,
    borderWidth: 1,
    borderColor: 'rgba(0,255,170,0.4)',
    position: 'absolute',
    bottom: 80,
    left: 16,
    right: 16,
  },
  manualButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFF',
    textAlign: 'center',
    flex: 1,
  },
});
