import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#000',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#000',
  },
  header: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  backArea: {
    padding: 4,
  },
  flex1: {
    flex: 1,
  },
  saveText: {
    color: '#FFA500',
    fontSize: 16,
    fontWeight: '600',
  },
  body: {
    flex: 1,
    backgroundColor: '#000',
  },
  previewContainer: {
    flex: 1,
    backgroundColor: '#000',
    marginBottom: 16,
    marginHorizontal: 15,
  },
  cameraPreview: {
    flex: 1,
    backgroundColor: '#000',
  },
  overlayContainer: {
    ...StyleSheet.absoluteFill,
  },
  gridOverlay: {
    ...StyleSheet.absoluteFill,
    overflow: 'hidden',
  },
  gridLineVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  gridLineHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  zoneOverlay: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#FFA500',
    backgroundColor: 'rgba(255,165,0,0.2)',
  },
  cornerHandle: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  cornerInner: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#FFA500',
  },
  rightButtons: {
    position: 'absolute',
    right: 16,
    top: 40,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  roundButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  loadingText: {
    fontSize: 14,
    color: '#FCD34D',
    marginTop: 2,
  },
  reconnectingOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  reconnectingText: {
    color: '#FFA500',
    marginTop: 12,
    fontSize: 14,
    fontWeight: '600',
  },
  reconnectingSubtext: {
    color: '#fff',
    marginTop: 4,
    fontSize: 12,
  },
  errorOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  errorText: {
    color: '#FF5252',
    fontSize: 14,
    marginBottom: 12,
  },
  retryButton: {
    marginTop: 12,
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#FFA500',
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  controls: {
    position: 'absolute',
    bottom: 40,
    right: 40,
  },
  muteBtn: {},
  circle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    fontSize: 28,
    color: 'white',
  },
  lineStyle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FFF',
  },
  switchButton: {
    position: 'absolute',
    right: 24,
    top: 24,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 20,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  marginIcon: {
    marginRight: 6,
  },
  fontStyle: {
    color: '#333',
    fontWeight: 'bold',
  },
  stallReasonText: {
    fontSize: 11,
    color: '#FCD34D',
    marginTop: 2,
  },
  svgOverlay: {
    ...StyleSheet.absoluteFill,
  },
  webViewContainer: {
    flex: 1,
    backgroundColor: '#000',
    overflow: 'hidden',
    opacity: 0.99,
  },
  muteButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
});
