import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '@constants/theme';
import { isTablet } from '@utils/responsive';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    backgroundColor: '#101820',
  },
  imageStyle: {
    width: '100%',
    height: '100%',
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
  },
  saveButton: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#00D9FF',
    width: 102,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonDisabled: {
    opacity: 0.5,
  },
  saveButtonText: {
    fontSize: 20,
    fontWeight: FONTS.weights.medium,
    color: COLORS.card,
  },
  instructionContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  instructionText: {
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  previewContainer: {
    flex: 1,
    alignItems: 'center',
  },
  previewWrapper: {
    width: 440,
    height: 403,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#1A2332',
  },
  cameraPreview: {
    width: '100%',
    height: '100%',
  },
  cornerHandle: {
    position: 'absolute',
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  cornerDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#00FFAA',
    borderWidth: 2,
    borderColor: '#FFF',
    shadowColor: '#00FFAA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 5,
  },
  cornerRing: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(0,255,170,0.5)',
  },
  fullscreenButton: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ===== BOTTOM CONTROLS - FIXED =====
  bottomControlsWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: 20, // Safe area for home indicator
  },
  bottomControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 20,
    marginHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(0,255,170,0.2)',
  },
  controlButton: {
    alignItems: 'center',
    gap: 8,
    minWidth: 80,
  },
  controlIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(10,30,25,0.8)',
    borderWidth: 2,
    borderColor: '#00FFAA',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#00FFAA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryButton: {
    backgroundColor: '#00FFAA',
    borderColor: '#00FFAA',
    shadowColor: '#00FFAA',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 8,
  },
  controlLabel: {
    fontSize: 13,
    fontWeight: FONTS.weights.medium,
    color: '#E5E7EB',
  },
  buttonIcon: {
    width: isTablet() ? 50 : 46,
    height: isTablet() ? 50 : 46,
  },
  instructionBanner: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    zIndex: 100,
  },
  instructionBox: {
    backgroundColor: 'rgba(10,15,30,0.95)',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
    paddingVertical: 11,
    paddingHorizontal: 17,
    alignSelf: 'center',
    borderRadius: 22,
  },
  drawingZone: {
    top: 'auto',
    bottom: 0,
  },
});
