import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '@constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0E1A',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#0A0E1A',
  },
  contentContainer: {
    paddingBottom: 20,
    paddingTop: 20,
  },
  logoContainer: {
    alignItems: 'center',
  },
  successBadgeContainer: {
    alignItems: 'center',
    paddingBottom: 20,
  },
  successText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
  },
  cameraCard: {
    marginHorizontal: 20,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    elevation: 10,
  },
  liveBadge: {
    position: 'absolute',
    top: 22,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(33,27,27,0.3)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 40,
    zIndex: 10,
  },
  liveIndicator: {
    width: 13,
    height: 13,
    borderRadius: 100,
    backgroundColor: COLORS.FF0000,
    marginRight: 5,
  },
  liveText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: FONTS.weights.medium,
    letterSpacing: 0.5,
  },
  aivasLogoContainer: {
    position: 'absolute',
    top: 22,
    right: 12,
    zIndex: 10,
  },
  aivasLogo: {
    fontSize: 20,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  streamWrapper: {
    width: '100%',
    height: 245,
    position: 'relative',
  },
  videoPlayerRoot: {
    flex: 1,
    width: '100%',
    minHeight: 0,
    alignSelf: 'stretch',
    position: 'relative',
    backgroundColor: '#000',
    overflow: 'hidden',
  },
  videoNativeSurface: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000',
  },
  micWebViewHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
    left: -100,
    top: -100,
    overflow: 'hidden',
  },
  webViewContainer: {
    flex: 1,
    backgroundColor: '#000',
    overflow: 'hidden',
  },
  streamOverlayContainer: {
    ...StyleSheet.absoluteFill,
    zIndex: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingIndicatorInOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  errorInOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
    padding: 20,
  },
  webView: {
    flex: 1,
    backgroundColor: '#000',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    color: '#fff',
    fontSize: 16,
    marginTop: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  loadingRetryButton: {
    marginTop: 24,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  loadingRetryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  errorOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
  },
  reconnectingOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  reconnectingText: {
    color: '#FFA500',
    fontSize: 18,
    fontWeight: '600',
    marginTop: 16,
    textAlign: 'center',
  },
  reconnectingSubtext: {
    color: '#fff',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
    opacity: 0.8,
  },
  retryButton: {
    paddingHorizontal: 30,
    paddingVertical: 12,
    backgroundColor: COLORS.main,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  cameraInfoFooter: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    marginHorizontal: 20,
    borderRadius: 22,
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  cameraIconContainer: {
    marginRight: 12,
  },
  cameraIcon: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#2A3142',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraIconText: {
    fontSize: 24,
  },
  cameraDetails: {
    paddingLeft: 20,
  },
  cameraName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  cameraSerial: {
    fontSize: 12,
    color: '#8B92A8',
    marginBottom: 6,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4CAF50',
    marginRight: 6,
  },
  statusText: {
    fontSize: 12,
    color: COLORS.main,
    fontWeight: '500',
  },
  cameraNameSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 16,
  },
  cameraNameLabel: {
    fontSize: 14,
    color: '#8B92A8',
    marginBottom: 12,
    fontWeight: '500',
  },
  editNameButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1F2E',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A3142',
    marginBottom: 8,
  },
  editIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  editNameInput: {
    flex: 1,
    fontSize: 15,
    color: '#fff',
    padding: 0,
    marginLeft: 10,
  },
  editNameText: {
    flex: 1,
    fontSize: 15,
    color: '#fff',
  },
  cameraNameHint: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 8,
    lineHeight: 18,
  },
  cameraNameError: {
    fontSize: 12,
    color: 'red',
    marginTop: 4,
    lineHeight: 18,
  },
  bottomSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.main,
    paddingVertical: 16,
    borderRadius: 40,
    marginBottom: 12,
    shadowColor: '#00A8E8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    marginRight: 8,
    textAlign: 'center',
  },
  arrowIcon: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    paddingVertical: 16,
    borderRadius: 40,
    borderWidth: 1.5,
    borderColor: '#2A3142',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginRight: 8,
  },
  cardImage: {
    marginLeft: 16,
  },
  styleViewBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  settingStyle: {
    flex: 1,
    alignItems: 'center',
  },
  marginStyle: {
    paddingRight: 20,
  },
  viewButtonBottom: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  positionButtonBottom: {
    position: 'absolute',
    right: 20,
  },
});
