import { StyleSheet } from 'react-native';
import { isTablet } from '@utils/responsive';
import { COLORS, FONTS } from '@constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 0,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    backgroundColor: '#101820',
  },
  imageStyle: {
    width: '100%',
    height: '100%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: isTablet() ? 20 : 12,
    paddingHorizontal: 14,
  },
  backBtn: { marginRight: 5, padding: 4 },
  headerTitle: {
    color: '#FFF',
    fontSize: 21,
    fontWeight: '700',
    marginLeft: 20,
  },
  modeSwitcher: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: isTablet() ? 20 : 13,
    marginVertical: isTablet() ? 16 : 8,
    backgroundColor: '#1A202C',
    marginHorizontal: 20,
    borderRadius: 8,
    paddingVertical: 4,
  },
  switchBtn: {
    paddingVertical: isTablet() ? 12 : 8,
    paddingHorizontal: isTablet() ? 40 : 30,
    borderRadius: 8,
    flexDirection: 'row',
    height: isTablet() ? 50 : 45,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1A202C',
    width: '45%',
  },
  switchBtnActive: {
    height: 45,
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchText: {
    color: '#7BAAC4',
    fontSize: 15,
    fontWeight: '500',
  },
  switchTextActive: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '700',
  },
  radarContainer: {
    alignItems: 'center',
    marginTop: isTablet() ? 20 : 12,
  },
  radarOuter: {
    width: 144,
    height: 144,
    borderRadius: 72,
    borderWidth: 2,
    borderColor: '#093B40',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanningText: {
    textAlign: 'center',
    color: '#D2FBFF',
    fontWeight: '600',
    fontSize: isTablet() ? 18 : 16,
    marginTop: isTablet() ? 30 : 23,
  },
  hintText: {
    textAlign: 'center',
    color: '#7AB0C5',
    fontSize: isTablet() ? 15 : 13,
    marginVertical: isTablet() ? 10 : 7,
  },
  devicesHeader: {
    flexDirection: 'row',
    paddingHorizontal: isTablet() ? 30 : 22,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: isTablet() ? 35 : 26,
    marginBottom: isTablet() ? 15 : 10,
  },
  devicesTitle: {
    color: COLORS.main,
    fontSize: 13,
    fontWeight: '700',
  },
  scanAgain: {
    color: COLORS.main,
    fontSize: 13,
    fontWeight: '600',
  },
  deviceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: isTablet() ? 25 : 16,
    backgroundColor: '#172A3A',
    borderRadius: 15,
    paddingVertical: isTablet() ? 18 : 14,
    paddingHorizontal: isTablet() ? 20 : 15,
    borderWidth: 1.5,
    borderColor: '#183647',
  },
  deviceLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    flexShrink: 1,
    marginRight: 12,
  },
  deviceInfo: { flex: 1 },
  deviceName: { color: '#FFF', fontWeight: '700', fontSize: isTablet() ? 18 : 16 },
  signalRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 3 },
  signalDot: { width: 7, height: 7, borderRadius: 4, marginRight: 2, backgroundColor: '#00FFAA' },
  signalLabel: { color: '#BEDCF1', fontSize: 13 },
  connectBtn: {
    backgroundColor: COLORS.main,
    borderRadius: 11,
    paddingVertical: isTablet() ? 10 : 7,
    paddingHorizontal: isTablet() ? 20 : 16,
    minWidth: isTablet() ? 90 : 75,
    flexShrink: 0, // Prevent button from shrinking
  },
  connectBtnText: {
    color: COLORS.background,
    fontWeight: FONTS.weights.medium,
    fontSize: isTablet() ? 18 : 14,
    textAlign: 'center',
  },
  bottomContainer: {
    paddingVertical: isTablet() ? 25 : 18,
    paddingBottom: isTablet() ? 15 : 9,
  },
  troubleBtn: { alignItems: 'center' },
  troubleText: { color: '#7BA5C2', fontSize: 14, textDecorationLine: 'underline' },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonIcon: {
    width: isTablet() ? 50 : 46,
    height: isTablet() ? 50 : 46,
  },
  viewScanning: {
    alignItems: 'center',
    marginVertical: 30,
  },
  contentContainer: { flex: 1 },
  flatList: { flex: 1 },
  flatListContainerStyle: { gap: 16, paddingBottom: 10 },
  listEmptyComponentTextStyle: {
    color: '#74BDEF',
    textAlign: 'center',
    marginTop: 20,
  },
  listEmptyComponentStyle: {
    flex: 1,
    justifyContent: 'center',
    minHeight: 200,
  },
  iconMargin: {
    marginRight: 12,
  },
  scanAgainOpacity: {
    opacity: 0.4,
  },
  styleRotate: {
    flexDirection: 'row',
  },
  cameraImageContainer: {
    width: 35,
    height: 35,
    borderRadius: 8,
    backgroundColor: 'rgba(0,217,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingContent: {
    backgroundColor: 'rgba(26, 42, 58, 0.95)',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#38E9FF',
  },
  loadingText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 15,
    textAlign: 'center',
  },
  textHeader: {
    color: '#C3C3C3',
    textAlign: 'center',
    paddingHorizontal: 50,
    fontSize: 16,
    fontWeight: FONTS.weights.regular,
    paddingVertical: 15,
  },
});
